import dotenv from "dotenv";
dotenv.config();
import { GoogleGenAI } from "@google/genai";
import puppeteer from "puppeteer";

const ai = new GoogleGenAI({
    apiKey: process.env.GEMINI_API_KEY
});

async function generateInterviewReport({
    jobDescription,
    resume,
    selfDescription
}) {
    try {
        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash",

            contents: `
You are an expert AI Interview Coach.

Analyze the candidate profile carefully.

INPUT:

Job Description:
${jobDescription}

Resume:
${resume}

Self Description:
${selfDescription}

Return ONLY valid JSON in this EXACT format:

{
  "title": "string",
  "matchScore": 85,

  "technicalQuestions": [
    {
      "question": "string",
      "intent": "string",
      "answer": "string"
    }
  ],

  "behavioralQuestions": [
    {
      "question": "string",
      "intent": "string",
      "answer": "string"
    }
  ],

  "skillGaps": [
    {
      "skill": "string",
      "severity": "high"
    }
  ],

  "preparationPlan": [
    {
      "day": 1,
      "focus": "string",
      "task": ["string", "string"]
    }
  ]
}

Rules:
- Return pure JSON only
- No markdown
- No explanation
- technicalQuestions must contain 5 objects
- behavioralQuestions must contain 3 objects
- skillGaps must contain 5 objects
- preparationPlan must contain 7 objects
`,

            config: {
                responseMimeType: "application/json"
            }
        });

        const data = JSON.parse(response.text);

        return {
            title: data.title || "Software Developer",

            matchScore: Number(data.matchScore) || 70,

            technicalQuestions: Array.isArray(data.technicalQuestions)
                ? data.technicalQuestions.map((item) => ({
                    question: item.question || "Technical Question",
                    intent: item.intent || "Assess technical knowledge",
                    answer: item.answer || "Provide clear explanation"
                }))
                : [],

            behavioralQuestions: Array.isArray(data.behavioralQuestions)
                ? data.behavioralQuestions.map((item) => ({
                    question: item.question || "Behavioral Question",
                    intent: item.intent || "Assess soft skills",
                    answer: item.answer || "Use STAR method"
                }))
                : [],

            skillGaps: Array.isArray(data.skillGaps)
                ? data.skillGaps.map((item) => ({
                    skill: item.skill || "Unknown Skill",
                    severity: ["high", "medium", "low"].includes(item.severity)
                        ? item.severity
                        : "medium"
                }))
                : [],

            preparationPlan: Array.isArray(data.preparationPlan)
                ? data.preparationPlan.map((item, index) => ({
                    day: Number(item.day) || index + 1,
                    focus: item.focus || "Interview Preparation",
                    task: Array.isArray(item.task)
                        ? item.task
                        : ["Study concepts", "Practice questions"]
                }))
                : []
        };

    } catch (error) {
        console.log(error);

        
    }
}

async function generatePdfFromHtml(htmlContent) {
    const browser = await puppeteer.launch()
    const page = await browser.newPage();
    await page.setContent(htmlContent, { waitUntil: "networkidle0" })

    const pdfBuffer = await page.pdf({
        format: "A4", margin: {
            top: "20mm",
            bottom: "20mm",
            left: "15mm",
            right: "15mm"
        }
    })

    await browser.close()

    return pdfBuffer
}

async function generateResumePdf({ resume, selfDescription, jobDescription }) {

    const resumePdfSchema = z.object({
        html: z.string().describe("The HTML content of the resume which can be converted to PDF using any library like puppeteer")
    })

    const prompt = `Generate resume for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}

                        the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
                    `

    const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: zodToJsonSchema(resumePdfSchema),
        }
    })


    const jsonContent = JSON.parse(response.text)

    const pdfBuffer = await generatePdfFromHtml(jsonContent.html)

    return pdfBuffer

}

export default {generateInterviewReport,generateResumePdf};








